#+TITLE: Docker
#+DATE: 24 March 2015
#+AUTHOR: (an introduction)
#+EMAIL: Richard Wall (@wallrj) <richard@the-moon.net>
#+REVEAL_THEME: night
#+REVEAL_TRANS: linear
#+REVEAL-SLIDE-NUMBER: t
#+REVEAL_ROOT: //cdn.jsdelivr.net/reveal.js/2.5.0/
#+OPTIONS: timestamp:nil author:nil num:nil toc:nil reveal_rolling_links:nil
#+OPTIONS: reveal_history:t
# Remove speaker notes
# awk 'BEGIN {skip=0} /^#\+BEGIN_NOTES/ { skip=1 } /^#\+END_NOTES/ {skip=0; next;} {if(skip==0) print $0}'

* Introduction and recap (5m)

  * Introduction and recap (5m)
  * Preparations (30m)
  * What is Docker? (5m)
  * Summary of Docker commands so far... (5m)
  * Tutorial Environment (5m)
  * Exercises (30m)
  * The `tutum/apache-php` Dockerfile (5m)
  * Next Steps (30m)
  * Questions? (5m)

* Virtual Machines

  * VirtualBox
  * VMWare
  * etc

  https://en.wikipedia.org/wiki/Virtual_machine

* System Virtual Machines

  * AKA Hardware virtualisation,
  * emulates foreign hardware environments and
  * machines have their own kernels

  http://en.wikipedia.org/wiki/Hardware_virtualization

* Vagrant

  * "Create and configure lightweight, reproducible, and portable development environments."
  * "Provisioners in Vagrant allow you to automatically install software, alter configurations, and more on the machine as part of the vagrant up process."
  * `vagrant up`

  https://www.vagrantup.com/

* Vagrant for server provisioning

  * OS installation
  * Storage set up
  * Network set up
  * Install packages
  * Upgrade packages

  https://en.wikipedia.org/wiki/Provisioning#Server_provisioning

* Vagrant for configuration management

  * Puppet
  * Chef

  https://en.wikipedia.org/wiki/Configuration_management#Operating_System_configuration_management

* Preparations (30m)

* Identify experts

  * Vagrant / Docker experts please stand up

* Software

  Install the following software on your laptop:

  * Git: http://git-scm.com/downloads
  * VirtualBox: https://www.virtualbox.org
  * Vagrant: https://docs.vagrantup.com/v2/installation

* Start the tutorial environment

  #+BEGIN_SRC sh

  git clone https://github.com/wallrj/docker-tutorial.git
  cd docker-tutorial
  vagrant up

  #+END_SRC

* What is Docker? (5m)

  #+BEGIN_QUOTE

  Docker is an open platform for developers and sysadmins to build, ship, and
  run distributed applications.

  Consisting of Docker Engine, a portable,
  lightweight runtime and packaging tool, and Docker Hub, a cloud service for
  sharing applications and automating workflows, Docker enables apps to be
  quickly assembled from components and eliminates the friction between
  development, QA, and production environments.

  As a result, IT can ship faster
  and run the same app, unchanged, on laptops, data center VMs, and any cloud.

  #+END_QUOTE

  https://www.docker.com/whatisdocker/

* Operating system level virtualisation

  * Containers share the same kernel as the host.
  * Low overhead, because
  * programs in virtual partitions use the operating system's normal system call interface and
  * do not need to be subjected to emulation or
  * be run in an intermediate virtual machine,
  * as is the case with whole-system virtualizers (such as VMware ESXi, QEMU or Hyper-V) and paravirtualizers (such as Xen or UML).
  * This form of virtualization also does not require support in hardware to perform efficiently.

  https://en.wikipedia.org/wiki/Operating-system-level_virtualization

* Docker Terminology
  * Container
  * Dockerfile
  * Entrypoint
  * Images
  * Layers
  * Copy-on-write
  * Pull
  * Expose ports
  * Volumes
  * Links

* Docker Components
  * Docker daemon
  * Docker client
  * Docker hub

* Docker Tutorial (30 minutes)

  https://www.docker.com/tryit/

* Summary of Docker commands so far... (5m)

* `docker version`

* `docker search`

* `docker pull`

* `docker run`

* `docker ps`

* `docker commit`

* `docker inspect`

* `docker push`

* Tutorial Environment (5m)

* Log in

  #+BEGIN_SRC sh

  # Change to the tutorial directory
  cd docker-tutorial

  # You may already have completed this step
  vagrant up

  # Log into the virtual machine
  vagrant ssh

  #+END_SRC

* The tutorial virtual machine

* Bare bones system

  Neither Apache or PHP present on tutorial VM!

  #+BEGIN_SRC sh

  vagrant@docker-tutorial:~$ php
  The program 'php' is currently not installed. You can install it by typing:
  sudo apt-get install php5-cli

  #+END_SRC

  #+BEGIN_SRC sh

  vagrant@docker-tutorial:~$ apache
  No command 'apache' found, did you mean:
   Command 'apache2' from package 'apache2-bin' (main)
  apache: command not found

  #+END_SRC

* Exercises (30m)

* Start a webserver

  #+BEGIN_SRC sh

  docker run --rm --detach --publish 80 tutum/apache-php
  docker ps

  #+END_SRC

  (note the port)

  #+BEGIN_SRC sh
vagrant@docker-tutorial:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                   NAMES
d10d4eec5ba1        tutum/apache-php:latest   "/run.sh"           14 seconds ago      Up 13 seconds       0.0.0.0:49154->80/tcp   compassionate_mcclintock

  #+END_SRC

* Access webserver from laptop

  * http://172.16.255.250:<PORT>

* Choose the webserver port

  #+BEGIN_SRC sh

  docker run --rm --detach --publish 8080:80 tutum/apache-php
  docker ps

  #+END_SRC

  http://172.16.255.250:8080

* Serve a custom page

  #+BEGIN_SRC sh

  docker run --rm --detach --publish 8081:80  --volume /vagrant/sample1:/app tutum/apache-php
  docker ps

  #+END_SRC

  http://172.16.255.250:8081

* The `tutum/apache-php` Dockerfile (5m)

  * Uploaded to Docker Hub
  * Built upon official Ubuntu base image
  * Apache and PHP packages installed
  * Composer installed
  * Apache and PHP configured
  * Container configured to serve files in /app
  * Entry point script added
  * Port exposed

  https://registry.hub.docker.com/u/tutum/apache-php/dockerfile/

* Next Steps (30m)

* Build an image

  * On your laptop:

  #+BEGIN_SRC sh
  cd docker-tutorial
  cd sample2
  edit Dockerfile
  #+END_SRC

  * And in the virtual machine:

  #+BEGIN_SRC sh
  cd /vagrant
  cd sample2
  docker build --tag=docker-tutorial/sample2 .
  docker run --rm --interactive --tty docker-tutorial/sample2 /bin/bash
  #+END_SRC

  * Edit Dockerfile and repeat

* Install Docker on your laptop

  https://docs.docker.com/installation/#installation

* Register at Docker Hub and push an image

  * Sign up with GitHub

  https://hub.docker.com/

* Use `compose` (fig) to bring up a micro-service application.

  eg Elastic Search, Logstash, Kibana

  https://github.com/ClusterHQ/docker-images

* Summary

* Questions? (5m)

* Thanks and links
  * Mix Radio: https://github.com/mixradio
  * Katja Durrani: https://github.com/katjad
  * Carl Hughes: https://github.com/codekipple
  * Kai Davenport: https://github.com/binocarlos
  * Richard Wall: https://github.com/wallrj
  * ClusterHQ: https://github.com/ClusterHQ
