FROM ubuntu:14.04
# Refer to the Dockerfile reference and extend this as required...
# https://docs.docker.com/reference/builder/
#
# `docker build --tag=docker-tutorial/sample2 .` to build an image,
# `docker run --rm --interactive --tty docker-tutorial/sample2 /bin/sh` to run the image interactively.
