# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$bootstrap = <<SCRIPT
set -e

# Install Docker
# See https://docs.docker.com/installation/ubuntulinux/
curl -sSL https://get.docker.com/ubuntu/ | sh

# Add vagrant user to the docker group
usermod -a -G docker vagrant

# Pre-cache some Docker images
docker pull ubuntu:14.04
docker pull tutum/apache-php
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.provision :shell, :inline => $bootstrap, :privileged => true
end
